server:
    port: 8761

spring:
    application:
        name: eureka-server

eureka:
    instance:
        hostname: "${HOSTNAME}"
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
    level:
        root: INFO
        com.netflix.discovery: DEBUG
        org.springframework.cloud.netflix.eureka.server: DEBUG
